In [21]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv2D,Conv1D, MaxPooling1D,Reshape, LSTM, Dropout, TimeDistributed, Input
from tensorflow.keras.datasets import mnist
import numpy as np

from tensorflow.keras.utils import to_categorical



In [17]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()
y_train.shape

(60000,)

In [22]:
x_train=x_train.reshape((-1,28,28,1))/255.0
# x_test=x_test.reshape((-1,28,28,1))/255.0
y_train = to_categorical(y_train)
# y_test = tf.keras.utils.to_categorical(y_test)
y_train.shape

(60000, 10)

In [26]:
model=Sequential()

model.add(Input(shape=(28,28,1)))
model.add((Conv2D(filters=6, kernel_size=(5,5), activation='relu')))
model.add(Flatten())
model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=10, activation='softmax'))
model.compile( loss=tf.keras.losses.CategoricalCrossentropy() , metrics=['accuracy'],optimizer=tf.keras.optimizers.SGD(0.01))
model.summary()


Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 24, 24, 6)         156       
_________________________________________________________________
flatten_3 (Flatten)          (None, 3456)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                34570     
Total params: 34,726
Trainable params: 34,726
Non-trainable params: 0
_________________________________________________________________


In [25]:
model.fit(x_train,y_train,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 12s 6ms/step - loss: 2.3006 - accuracy: 0.1123
Epoch 2/10
1875/1875 [==============================] - 12s 6ms/step - loss: 2.3000 - accuracy: 0.1124
Epoch 3/10
1875/1875 [==============================] - 11s 6ms/step - loss: 2.2990 - accuracy: 0.1124
Epoch 4/10
1875/1875 [==============================] - 12s 6ms/step - loss: 2.2977 - accuracy: 0.1129
Epoch 5/10
1875/1875 [==============================] - 12s 6ms/step - loss: 2.2955 - accuracy: 0.1155
Epoch 6/10
 814/1875 [============>.................] - ETA: 6s - loss: 2.2932 - accuracy: 0.1204

KeyboardInterrupt: 

In [14]:
# model.fit(x_train,y_train,batch_size=32,epochs=5)
w1=((model.layers[0].weights)[0]).numpy()
w2=((model.layers[0].weights)[1]).numpy()

print(w1.shape)


(2, 2, 1, 2)


In [16]:
y_train=np.ones((1,4,2))*0.1

In [8]:
# for i in range(2500):
#     for j in range(10):
#         w1[i][j]=0.01
# for i in range(10):
#     w2[i]=0.01

# w=[w1,w2]
# model.layers[2].set_weights(w)


In [17]:
print(w1.shape)

(2, 2, 1, 2)


In [18]:
for a in range(2):
    for b in range(2):
        for c in range(1):
            for d in range(2):
                w1[a][b][c][d]=0.01

for i in range(2):
    w2[i]=0.01

w=[w1,w2]
model.layers[0].set_weights(w)


In [19]:

# model.fit(x_train,y_train,batch_size=1,epochs=1)

with tf.GradientTape() as tape:
    y_pred=model(x_train)
    # print(y_pred)
    loss=tf.keras.losses.MeanSquaredError()(y_train,y_pred)
    # print(loss)
    grads=tape.gradient(loss,model.trainable_variables)
    print(grads)
    


[<tf.Tensor: shape=(2, 2, 1, 2), dtype=float32, numpy=
array([[[[-0.0103, -0.0103]],

        [[-0.0175, -0.0175]]],


       [[[-0.0463, -0.0463]],

        [[-0.0535, -0.0535]]]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.072, -0.072], dtype=float32)>]


In [11]:
print(model.layers[0].weights[0].numpy())

[[[[0.01 0.01]]

  [[0.01 0.01]]]


 [[[0.01 0.01]]

  [[0.01 0.01]]]]
