In [2]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv2D,Conv1D, MaxPooling1D,Reshape, LSTM, Dropout, TimeDistributed, Input
from tensorflow.keras.datasets import mnist
import numpy as np

from tensorflow.keras.utils import to_categorical



In [9]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()
y_train.shape

(60000,)

In [10]:
x_train=x_train.reshape((-1,28,28,1))/255.0
# x_test=x_test.reshape((-1,28,28,1))/255.0
y_train = to_categorical(y_train)
# y_test = tf.keras.utils.to_categorical(y_test)
y_train.shape

(60000, 10)

In [11]:
model=Sequential()

model.add(Input(shape=(28,28,1)))
model.add((Conv2D(filters=5, kernel_size=(5,5), activation='relu')))
model.add(Flatten())
# model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=10, activation='softmax'))
model.compile( loss=tf.keras.losses.CategoricalCrossentropy() , metrics=['accuracy'],optimizer=tf.keras.optimizers.SGD(0.01))
model.summary()


Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 24, 10, 5)         255       
_________________________________________________________________
flatten_2 (Flatten)          (None, 1200)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                12010     
Total params: 12,265
Trainable params: 12,265
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.fit(x_train,y_train,epochs=10)

2022-05-27 15:14:33.612314: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2022-05-27 15:14:33.629504: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2899885000 Hz


Epoch 1/10
1875/1875 [==============================] - 167s 89ms/step - loss: 0.7399 - accuracy: 0.7932
Epoch 2/10
1875/1875 [==============================] - 165s 88ms/step - loss: 0.3043 - accuracy: 0.9119
Epoch 3/10
  48/1875 [..............................] - ETA: 2:49 - loss: 0.2623 - accuracy: 0.9192

KeyboardInterrupt: 

In [12]:
# model.fit(x_train,y_train,batch_size=32,epochs=5)
w1=((model.layers[0].weights)[0]).numpy()
w2=((model.layers[0].weights)[1]).numpy()

print(w1.shape)


(5, 5, 2, 5)


In [16]:
y_train=np.ones((1,4,2))*0.1

In [8]:
# for i in range(2500):
#     for j in range(10):
#         w1[i][j]=0.01
# for i in range(10):
#     w2[i]=0.01

# w=[w1,w2]
# model.layers[2].set_weights(w)


In [17]:
print(w1.shape)

(2, 2, 1, 2)


In [18]:
for a in range(2):
    for b in range(2):
        for c in range(1):
            for d in range(2):
                w1[a][b][c][d]=0.01

for i in range(2):
    w2[i]=0.01

w=[w1,w2]
model.layers[0].set_weights(w)


In [19]:

# model.fit(x_train,y_train,batch_size=1,epochs=1)

with tf.GradientTape() as tape:
    y_pred=model(x_train)
    # print(y_pred)
    loss=tf.keras.losses.MeanSquaredError()(y_train,y_pred)
    # print(loss)
    grads=tape.gradient(loss,model.trainable_variables)
    print(grads)
    


[<tf.Tensor: shape=(2, 2, 1, 2), dtype=float32, numpy=
array([[[[-0.0103, -0.0103]],

        [[-0.0175, -0.0175]]],


       [[[-0.0463, -0.0463]],

        [[-0.0535, -0.0535]]]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.072, -0.072], dtype=float32)>]


In [11]:
print(model.layers[0].weights[0].numpy())

[[[[0.01 0.01]]

  [[0.01 0.01]]]


 [[[0.01 0.01]]

  [[0.01 0.01]]]]
